# Generated by Django 3.1.5 on 2021-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('theme', models.TextField(max_length=1500, verbose_name='Тема обращения')),
                ('comment', models.TextField(max_length=1500, verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
            },
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='story',
            field=models.TextField(max_length=1500, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='people',
            name='story_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='people',
            name='story_ky',
            field=models.TextField(max_length=1500, null=True, verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='people',
            name='story_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='История'),
        ),
    ]
