# Generated by Django 3.1.5 on 2021-04-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210312_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterpreneurship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя предпринимателя')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Имя предпринимателя')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Имя предпринимателя')),
                ('name_ky', models.CharField(max_length=200, null=True, verbose_name='Имя предпринимателя')),
                ('text', models.TextField(max_length=1500, verbose_name='Текст')),
                ('text_ru', models.TextField(max_length=1500, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(max_length=1500, null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(max_length=1500, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Соц. предпринимательство',
                'verbose_name_plural': 'Соц. предпринимательство',
            },
        ),
        migrations.CreateModel(
            name='EnterpreneImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('enterpre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.enterpreneurship')),
            ],
            options={
                'verbose_name': 'Изображение соц. предпринимательства',
                'verbose_name_plural': 'Изображения соц. предпринимательства',
            },
        ),
    ]
