# Generated by Django 3.1.5 on 2021-04-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_enterpreneimage_enterpreneurship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpreneurship',
            name='text',
            field=models.TextField(max_length=15000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enterpreneurship',
            name='text_en',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enterpreneurship',
            name='text_ky',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='enterpreneurship',
            name='text_ru',
            field=models.TextField(max_length=15000, null=True, verbose_name='Текст'),
        ),
    ]
