from news.views.forum import *
from news.views.gallery import *
from news.views.himaya import *
from news.views.himaya_men import *
from news.views.himaya_ch import *
from news.views.index import *
from news.views.locale import *
from news.views.news_more import *
from news.views.news import *
from news.views.newspaper import *
from news.views.open_pdf import *
from news.views.payment_for_me import *
from news.views.payment import *
from news.views.selectlanguage import *